[package]
name = "test-sval"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]

[dev-dependencies]
fnv = "1.0"
indexmap = { path = "..", features = ["sval"] }
sval = { version = "2", features = ["derive"] }
sval_test = "2"
